### ISSUE TITLE
Error: Cannot overwrite a zero-length range

### ISSUE THREAD

**Issue by P4sca1** [nuxt/module-builder#102]
Reproduction: https://github.com/P4sca1/nuxt-headlessui/tree/f31e7b61b52082069780c5c13141587fd5808eb5

1. Clone the repo
2. Install dependencies with `yarn`
3. Run `yarn prepack`

After upgrading all my dev dependencies, I start to get the following error when running `nuxt-module-build`:
```
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
```
CI pipeline logs: https://app.circleci.com/pipelines/github/P4sca1/nuxt-headlessui/140/workflows/01cf5252-740c-4d05-a15f-6ee88bb3217e/jobs/129

**Comment by danielroe** [comment]
This is a rollup bug that was fixed in 3.20.6. You should be able to update your lockfile/rollup dependency and things should work again.
