### ISSUE TITLE
Feature: the `addComponentsDir` add a import by name options

### ISSUE THREAD

**Issue by zhangmo8** [nuxt/module-builder#106]
I'm refactoring my module repo with `addComponentDirs` or `nuxt.hoos('components:dirs')`

At present, some of components support both function calls and templates. In order to facilitate the call, I bind the template writing to the function, but in fact, I need the template to be added as a component, rather than a function that default goes out.

now the reslut is 
```
import { default as __nuxt_component_0 } from "/_nuxt/@fs/***"
```

I hope It's will be this

```
addComponentsDir({
  path: 'node_modules/packageName/ui'
   transpile: true,
   ...options
   importName: 'someComponent'
})

// then 

import { someComponent as __nuxt_component_0 } from "/_nuxt/@fs/***"
```

**Comment by zhangmo8** [comment]
I write a unplugin for it.And now it's resolved

**Comment by danielroe** [comment]
You can use `addComponent` with `export: 'someComponent'` as one of the options.

**Comment by zhangmo8** [comment]
I have used the `appComponent` before. Now I want to use `appComponentsDir` to reconstruct it.

Because `appComponentsDir` will bring in automatically, and then I just need to deal with style-related stuff.

May I submit a pr to do it? @danielroe

**Comment by danielroe** [comment]
@zhangmo8 Yes, indeed! Why not open an issue at https://github.com/nuxt/nuxt/ with a suggested approach to discuss first?
