### ISSUE TITLE
having a .git folder creates issues

### ISSUE THREAD

**Issue by acidjazz** [nuxt/module-builder#108]
When writing a module i have a very strange issue - the module works fine and the composables are fine - but when i `git init .` and it creates a `.git` folder i get tons of errors, composables cannot be found and it looks for a $setup.MyModule  function, removing the `.git` and restarting  `pnpm run dev`  resolves all issues, anyone else get this?

**Comment by acidjazz** [comment]
if i rename the folder to anything else the module and playground work perfect, very strange

**Comment by danielroe** [comment]
Are you still experiencing this? Would you be able to provide a reproduction?

**Comment by danielroe** [comment]
If you can still reproduce, feel free to provide a reproduction and I'll look in to this.
