### ISSUE TITLE
Does not wait for hook:rollup to complete before finishing the script

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/module-builder#120]
I'm creating a module but it also has a layer directory. I think the method I want to use, most in-sync with the docs, is to simply copy the layer directory from source into dist. So to do this I've adjusted `prepack` in my module to:
```
...
"prepack": "nuxt-module-build && npm run copy-layer",
...
```

Where the `copy-layer` nom script will copy layer files.

However, when run like this, the build is not complete when copy-layer is called. I think this is because the hook function has not finished..

I'm not sure if this is an issue, possibly here, or possible in the unjs/mkdist repo - if it is an issue that needs to be addressed at all that is...

--edit--
I can confirm that by adding a small sleep command between the 2, that it will work.

**Comment by danielroe** [comment]
So sorry for the long delay on this. Can you provide a reproduction? 🙏

**Comment by silverbackdan** [comment]
Hi @danielroe so sorry for my lack of reply, definitely OK to close and if I come across this to reproduce I will. I believe it's still happening but my sleep command is in place for the time being.
