### ISSUE TITLE
How to reference a JSON file in a component?

### ISSUE THREAD

**Issue by timb-103** [nuxt/module-builder#149]
I'm trying to import a JSON file in a vue component, this is how I do it current in a non-module build: 

`import List from "~/src/json/list.json"`

I've tried adding the json file to assets in the runtime folder, but can't figure it out.

**Comment by danielroe** [comment]
Could you provide a reproduction that shows what you are doing? If it and the Vue components are both in the runtime directory, I would use a relative import.

**Comment by danielroe** [comment]
Closing as this is an old issue that needs more info.
