### ISSUE TITLE
[feature request] support mts and cts declaration files

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/module-builder#151]
Context 

- https://github.com/unjs/unbuild/pull/273
- https://github.com/unjs/unbuild/pull/226

This changes are integrated in the latest version of unbuild : https://github.com/unjs/unbuild/releases/tag/v2.0.0-rc.0

Supporting them at the `module-builder` level will make it possible to support dual cjs/mjs with valid declaration types without workarounds.

The following package.json should work without a warning :  

```json
  "exports": {
    ".": {
      "require": {
        "types": "./dist/module.d.cts",
        "default": "./dist/module.cjs"
      },
      "import": {
        "types": "./dist/module.d.mts",
        "default": "./dist/module.mjs"
      },
      "types": "./dist/module.d.ts",
      "default": "./dist/module.mjs"
    }
  },
  "main": "./dist/module.cjs",
  "module": "./dist/module.mjs",
  "types": "./dist/types.d.ts",
  "files": [
    "dist",
    "*.d.ts",
    "*.cjs",
    "*.mjs"
  ],
```

**Comment by danielroe** [comment]
unbuild v2 is not yet released. when it is, this should be pretty automatic.
