### ISSUE TITLE
Register dynamic server routes not working

### ISSUE THREAD

**Issue by samk-dev** [nuxt/module-builder#153]
Hello,

I am working on a module that requires registering dynamic server routes. checking `nuxt-kit` docs found `addServerHandler`.
With static route name everything works as expected but using the `[param].ts` is not working or maybe I am using it wrong. It only shows the playground `app.vue`

`module.ts`

```ts
 addServerHandler({
    route: "/api/hello/[name]",
    handler: resolver.resolve("./runtime/server/api/hello/[name].get.ts"),
    method: "GET",
});
```

`runtime/server/api/hello/[name].get.ts`

```ts
export default defineEventHandler(
  (event) => `Hello, ${event.context.params?.name}!`
);
```

[reproduction repo](https://github.com/samk-dev/dynamic-server-routes-nuxt-module-bug-reproduction)

ps: I don't know if I filed the issue in the correct repository  or not 😅

Thanks in advance

**Comment by danielroe** [comment]
The route should be `/api/hello/:name`

**Comment by samk-dev** [comment]
you are a legend, thanks a lot 🙏🏼
