### ISSUE TITLE
can't generate complex types

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/module-builder#154]
I've had this issue in a few of my modules, I had to work around it by manually creating a `.d.ts` file adjacent to my source file. 
I'm not sure if this is related to `typescript`, `unbuild`, `rollup` or `untyped` ... 
Please have a look at this [commit](https://github.com/Hebilicious/authjs-nuxt/pull/70/commits/2a3fc2e3094a07dd545ac6573ae46ddcf08be0f8) to understand the bug.

Without this declaration file, the generated file in `dist/runtime/lib/client.d.ts` is *empty*. (There is no warning or error in the console when running the build command)

**Comment by danielroe** [comment]
I think this is likely an issue upstream in `mkdist`. Happy for you to create an issue there to track 🙏
