### ISSUE TITLE
Problem defining sass/scss namespace using vite config

### ISSUE THREAD

**Issue by jenseo** [nuxt/module-builder#172]
Hi there,
I have a problem defining sass namespaces in the nuxt config, to be able to use them in all components without explicitly importing them in each component. 

It works perfectly in dev mode, but when running the `prepack` command, it does not work. Here's the config:

```
    nuxt.options.vite = {
      ...nuxt.options.vite,
      css: {
        preprocessorOptions: {
          scss: {
            additionalData: `
              @use "@vst-common/css/scss/variables" as variables;
              @use "@vst-common/css/scss/mixins/breakpoints" as breakpoints;
              $vst-fonts-path: "@vst-common/css/fonts";
              @import "@vst-common/css/scss/fonts";
            `,
          },
        },
      },
    };
```

To be perfectly clear, the above works perfectly fine in dev mode, but when running prepack I'm getting the following error:

`sass.Exception [Error]: There is no module with the namespace "breakpoints".`

I'm not sure if this is the correct approach and if I should be able to use the vite additional data option when bundling the module, but I haven't really found a solution to it doing some other way either. 

Looking in the source code of module builder, it looks like the inputs for the builder are the `module.ts` file and the `runtime` directory. It seems to me that at least in my case, it parses the files in the runtime directory first, before getting to the module file. Could I influence the order in some way, to make sure the variables are set globally before parsing the files for instance?

I would be so happy for some advice here!

**Comment by ennioVisco** [comment]
> Hi there, I have a problem defining sass namespaces in the nuxt config, to be able to use them in all components without explicitly importing them in each component.
> 
> It works perfectly in dev mode, but when running the `prepack` command, it does not work. Here's the config:
> 
> ```
>     nuxt.options.vite = {
>       ...nuxt.options.vite,
>       css: {
>         preprocessorOptions: {
>           scss: {
>             additionalData: `
>               @use "@vst-common/css/scss/variables" as variables;
>               @use "@vst-common/css/scss/mixins/breakpoints" as breakpoints;
>               $vst-fonts-path: "@vst-common/css/fonts";
>               @import "@vst-common/css/scss/fonts";
>             `,
>           },
>         },
>       },
>     };
> ```
> 
> To be perfectly clear, the above works perfectly fine in dev mode, but when running prepack I'm getting the following error:
> 
> `sass.Exception [Error]: There is no module with the namespace "breakpoints".`
> 
> I'm not sure if this is the correct approach and if I should be able to use the vite additional data option when bundling the module, but I haven't really found a solution to it doing some other way either.
> 
> Looking in the source code of module builder, it looks like the inputs for the builder are the `module.ts` file and the `runtime` directory. It seems to me that at least in my case, it parses the files in the runtime directory first, before getting to the module file. Could I influence the order in some way, to make sure the variables are set globally before parsing the files for instance?
> 
> I would be so happy for some advice here!

It was working the other way in version `0.2.0`. Did you find a way to solve it?
