### ISSUE TITLE
Question/Proposition previous module template for nuxt 3 (using strapi module as a reference)

### ISSUE THREAD

**Issue by Baroshem** [nuxt/module-builder#21]
Hi guys,

Really nice module template that I was looking for recently. The previous modules I was building for Nuxt 3 followed Strapi module apprach so I have few questions/propositions:

1. What about the example folder with a nuxt 3 project for easy testing? I really liked this approach as there was an instant possibility to test the module using simple page and a nuxt.config.ts
2. What about docs? I really liked the Docus way of writing docs. Maybe it would be reasonable to provide a simple docs project so that contributors and module creators could easily build docs for their modules and deploy them to Netlify/Vercel/any other. I have seen many very good and useful modules that were lacking a proper docs explaining how to use the module. By having the docs in the module builder we could encourage module authors to also write docs as they do not have to do it from scratch.

**Comment by pi0** [comment]
Thanks for kind words Jakub  💚  

I would recommend following this starter template and playground: https://github.com/nuxt/starter/tree/module

As for docs, you are free to choose the deployment and writing framework. docus is being merged to content v2 in the upcoming weeks. It would be probably overkilling if included in the starter but we are also thinking of a system to automatically generated documentation based on module's meta and jsdocs (using [unjs/untyped](https://github.com/unjs/untyped)) that can be rendered in https://modules.nuxtjs.org/ without extra setup.

**Comment by Baroshem** [comment]
I see

Then the question 1 is obsolete ;)

Regarding question two, that completely answers my question. Thanks for claryfing that. Looking forward to this untyped automatic docs generation. Would be awesome to have that

My questions are answered. You can close this issue
