### ISSUE TITLE
 Missing "./playground/.nuxt/css" export in "my-module" package

### ISSUE THREAD

**Issue by MohammadS3dd** [nuxt/module-builder#22]
i'm following guides for making a new module and this weird error keeps popping up. 
![image](https://user-images.githubusercontent.com/58886172/151865318-08182b82-0c73-4950-ab2f-0390ceda0fd3.png)

**Comment by MohammadS3dd** [comment]
i fidgeted with this and turns out this only occurs in windows. doesn't matter if i run the project with yarn, npm or pnpm... but everything works fine with wsl on the same project.

**Comment by lihbr** [comment]
Experiencing the same one here, still troubleshooting a temp fix here~

I'm running Node v16.13.0 and I was able to reproduce using the starter.

**Comment by danielroe** [comment]
~A temporary workaround is to name the `exports` section of your `package.json` to `_exports` (i.e. disable it but without removing it from the file, so you can re-activate once this is resolved).~

For now, just create a minimal `package.json` file in your `playground/` directory.

**Comment by pi0** [comment]
Can you please provide a reprodution?

**Comment by Intevel** [comment]
https://github.com/nuxt/nuxt.js/issues/13403

**Comment by ricardogobbosouza** [comment]
i think this has been resolved

**Comment by Intevel** [comment]
Yes, thank you @danielroe ❤️

**Comment by danielroe** [comment]
Do you mean this is no longer replicable, or that it is resolved with my workaround?

**Comment by Intevel** [comment]
It's solved with a package.json for me. @danielroe

**Comment by Intevel** [comment]
I think this can be closed. Or maybe we can fix this bug in general by creating a `package.json`? 
So that when I create a new module already in the `playground` is automatically created a `package.json.`
