### ISSUE TITLE
Importing directly from module entry points is not allowed.

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/module-builder#220]
This error is given in the playground with the default import of the module, following the scaffolding instructions

### Reproduction:
- `npx nuxi init -t module my-module`
- `cd my-module && npm dev` (or any other package manager one uses)

<img width="882" alt="image" src="https://github.com/nuxt/module-builder/assets/740025/64370d63-70e8-458a-91c5-762914567fc6">

**Comment by danielroe** [comment]
I can't reproduce this following those steps... Are you importing from your module in the plugin?

**Comment by ennioVisco** [comment]
I apologize. I added one line extra from the scaffold that was the import of the package name from the module.
I didn't image that would have this effect, nor the error helped me get it 😅
By moving it to an external file, the issue is solved. Thanks a lot 🙏
