### ISSUE TITLE
Nuxt v2 Type Support

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/module-builder#23]
Hey, I've implemented the module-builder on 2 projects so far and has been pretty smooth, great job with it.

One issue I've noticed is that the nuxt v2 types no longer work due to `@nuxt/types` not being augmented.

It's not ideal to ship augmentation that may not be used but given that a lot of people are still stuck on v2, it would be nice to keep types working for them?

All good if you'd prefer to have module authors opt-in to that, I can still augment it myself after all.

**Comment by pi0** [comment]
Seems a good idea if we support an opt-in flag to generate nuxt 2 compatible types. PR welcome!


Side note: Generally, I would advise dropping Nuxt 2 (w/o bridge & nitro). Besides types, it is too much trouble handling behavior differences and mainly why bridge project exists :D
