### ISSUE TITLE
Playground Typecheck error

### ISSUE THREAD

**Issue by dvdmlln** [nuxt/module-builder#236]
Hi,

I ran into some issues when using typecheck on my module.
Previously, my `tsconfig.json` looked like this
```json
{
  "extends": "./playground/.nuxt/tsconfig.json"
}
```
and everything worked using `nuxi typecheck`.

After I changed the extends path to `./.nuxt/tsconfig.json`, just like when you create a new module with `npx nuxi init -t module`, the typechecks won't work anymore.

See [this reproduction](https://github.com/dvdmlln/nuxt-module-typecheck).
`npm run typecheck1` doesn't work because the auto-imports from my module are missing and the @ alias in the playground can't be resolved.
`npm run typecheck2` only fails because of the playground @ alias.

Best regards
David

**Comment by danielroe** [comment]
1. Yes, you need to run `dev:prepare` before checking types - using `vue-tsc --noEmit` is correct for a 
2. The typecheck in root directory will correctly check your module but _not_ the playground, so you should exclude it and run a second typecheck within your playground directory 

Updated module template - thanks for the ping: https://github.com/nuxt/starter/commit/2dba71f74f2e9be05d06784dd5462e44b2299fbc
