### ISSUE TITLE
After build, lang=“ts" for script tag  is missing, the intellisense for component is not available

### ISSUE THREAD

**Issue by kongku** [nuxt/module-builder#239]
the sfc use options style with typescript, as follow:
```vue
<script lang="ts">
export default defineComponent({
  pros:{
     foo:{
       type: String,
        default: "bar"
     }
  }
})
</script>
```
after build:
```vue
<script>
export default defineComponent({
  pros:{
     foo:{
       type: String,
        default: "bar"
     }
  }
})
</script>
```

**Comment by BobbieGoede** [comment]
I believe this is intended behavior (not the lack of intellisense, but the untyped `.vue` file), files are transformed and the types should be extracted into a `.d.ts` file according to the [readme](https://github.com/nuxt/module-builder#dist-files). Can you elaborate on what issue you are running into? If you could provide a reproduction I'll take a look at it 🙏

**Comment by danielroe** [comment]
This is now resolved in `unbuild` v3 (and will be in the upcoming v1 release of module-builder).
