### ISSUE TITLE
Could not resolve import "#app"

### ISSUE THREAD

**Issue by trandaison** [nuxt/module-builder#242]
I created a module https://github.com/trandaison/nuxt-3-auth, the playground is working perfectly.
However, when I run `npm run prepack`, I got this error

```
(node-resolve plugin) Could not resolve import "#app" in /nuxt-3-auth/src/runtime/services/AuthStorage.ts using imports defined in /nuxt-3-auth/package.json.
(node-resolve plugin) Could not resolve import "#app" in /nuxt-3-auth/src/runtime/services/AuthStorage.ts using imports defined in /nuxt-3-auth/package.json.
"#app" is imported by "src/runtime/services/AuthStorage.ts", but could not be resolved – treating it as an external dependency.

 WARN  Build is done with some warnings:
- Inlined implicit external #app

 ERROR  Exiting with code (1). You can change this behavior by setting failOnWarn: false . 
```
![Screenshot 2024-03-19 at 11 17 13](https://github.com/nuxt/module-builder/assets/13447235/8e4aa753-2a33-49d0-a096-2aa3b2baced7)

Since `AuthStorage.ts` is not using any import from `#app` anymore, I don't know why it still throws this error.

=====
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.15.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

**Comment by trandaison** [comment]
My workaround is set `failOnWarn: false` by create a `build.config.ts`

```ts
import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  failOnWarn: false,
});
```

However, I think this is a bug, should be fixed in the module builder itself, and the docs should show an example how to custom the build config as well.

**Comment by danielroe** [comment]
The reason this is happening is that your module is importing _types_ from the runtime code, which itself is augmenting `#app`.

Instead, you should likely extract your types into a location where they can be shared between your runtime and build-time code.

If you do add config, it should likely be to add `#app` to your externals, like this:

```ts
import { defineBuildConfig } from "unbuild"

export default defineBuildConfig({
  externals: ['#imports', '#app'],
})
```

We may be able to improve this experience as having shared types between build/runtime is often necessary.
