### ISSUE TITLE
"bundlephobia is inaccessible" when using Shields.io badges.

### ISSUE THREAD

**Issue by johnson86tw** [nuxt/module-builder#273]
<img width="185" alt="截圖 2024-05-21 下午3 39 01" src="https://github.com/nuxt/module-builder/assets/31992185/d4a201ae-2f09-4d8a-a076-5083850f2f07">

https://bundlephobia.com/package/@vue-dapp/nuxt

<img width="1573" alt="截圖 2024-05-21 下午3 38 08" src="https://github.com/nuxt/module-builder/assets/31992185/066224e2-ecc2-4102-b5f2-515363546158">

**Comment by danielroe** [comment]
This feels like a bug in bundlephobia, not really something to fix here.

**Comment by johnson86tw** [comment]
@danielroe yeah, I agree. But is there a way to use index.ts instead of module.ts as the entry point?

**Comment by danielroe** [comment]
It would be possible to do by hooking into unbuild options, but I wouldn't want to support it as I'm not aware of a need to do so, and it introduces complexity.
