### ISSUE TITLE
Node 20 not supporting prepack script (Module Author)

### ISSUE THREAD

**Issue by leopradac** [nuxt/module-builder#278]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

_I will use npm as a sample, feel free to replicate it with yarn, pnpm, or bun._

Following the [Module Author Guide](https://nuxt.com/docs/guide/going-further/modules):

npx nuxi init -t module my-module
once it is finished

```
npm run dev:prepare
npm run prepack
```
It will retrieve

```
ℹ Building my-module
ℹ Cleaning dist directory: ./dist
```
And that's it, it gets stuck there.

It happens to me while
- using nuxt, @nuxt-kit, @nuxt-schema at "3.11.2"
- node 20

Those facing the same issue so far the only workaround for me was switching to node18.

### Describe the bug

prepack script (module build) gets stuck while cleaning dist directory

### Additional context

Already been tested in MacOS and Ubuntu.
Also tried two Node20 versions: v20.13.1 and v20.11.0.
Switched to Node v18.20.3 with the exact same project and works perfectly fine.

### Logs

```shell-script
ℹ Building my-module
ℹ Cleaning dist directory: ./dist
```

**Comment by arashsheyda** [comment]
I'm experiencing the same issue, here is a fresh project on [stackblitz for reproduction](https://stackblitz.com/~/github.com/nuxt/starter/tree/module)

**Comment by userquin** [comment]
try adding `nuxt-module-build prepare && ` to the `prepack` script:
`"prepack": "nuxt-module-build prepare && nuxt-module-build build",`

**Comment by arashsheyda** [comment]
@userquin thanks! solved my problem

**Comment by userquin** [comment]
I'm going to file an issue in the starter template and send the corresponding PR.

**Comment by danielroe** [comment]
Is someone experiencing an issue even after running `dev:prepare`? And if so do you have the updated `tsconfig.json` [here](https://github.com/nuxt/starter/blob/module/tsconfig.json#L2) and the [updated `dev:prepare` script](https://github.com/nuxt/starter/blob/module/package.json#L24)?

**Comment by danielroe** [comment]
Closing as it seems this is not reproducible with latest starter.
