### ISSUE TITLE
ERROR  could not parse module 

### ISSUE THREAD

**Issue by adhamfarrag** [nuxt/module-builder#28]
Hi, whenever I try to create a module I get this error.

<img width="980" alt="Screen Shot 2022-02-22 at 4 50 10 AM" src="https://user-images.githubusercontent.com/23562275/155024842-9bfddbbe-39df-484a-bec8-9a3190d335e4.png">

**Comment by danielroe** [comment]
Likely your `npx` is running a cached version of `nuxi`. Try `npx nuxi@latest init -t module my-module` instead.

**Comment by adhamfarrag** [comment]
@danielroe cleared cache and tried again. Didn't work.

**Comment by adhamfarrag** [comment]
@danielroe It worked. Thanks. :) 

For future visitors, use `rm -rf ~/.npm/_npx` to clear `npx` cache.
