### ISSUE TITLE
build command creates symlink from dist to src

### ISSUE THREAD

**Issue by markbrockhoff** [nuxt/module-builder#288]
Hi, I recently encountered an issue while trying to create a nuxt module within a turborepo project.
It seems like the build command only generates a symlink from the dist/runtime folder to src/runtime. This was causing some issues for me when turborepo tried to restore the build cache containing the symlink.

I'm not sure if there's a reason for the symlink within the dist folder but I found it a bit strange so I wanted to report the issue here.
The original issue raised for turborepo including a reproduction can be found here: https://github.com/vercel/turbo/issues/8476

**Comment by danielroe** [comment]
The symlink should only be created in stub mode. It's removed and a directory is created when building.

**Comment by markbrockhoff** [comment]
I see, then this is not a nuxt related issue and only related to the handling of symlinks inside turborepo. Thanks for clarification @danielroe.
