### ISSUE TITLE
Incorrect `d.ts` file generation from `runtime` folder

### ISSUE THREAD

**Issue by alSergey** [nuxt/module-builder#290]
### Describe the bug

The following type is generated in the file `dist/runtime/store/store.d.ts`

```ts
export declare const useAuthStore: () => {
    getAuthInfo: () => Promise<void>;
    authInfo: Readonly<import("vue").Ref<{
        readonly userId?: number | undefined;
        readonly login?: string | undefined;
    } | undefined>>;
    isLoadingAuthInfo: Readonly<import("vue").Ref<boolean>>;
    authInfoError: Readonly<import("vue").Ref<Readonly<unknown>>>;
};
```

The following type should be generated

```ts
export declare const useAuthStore: () => {
    getAuthInfo: () => Promise<void>;
    authInfo: {
        readonly userId?: number | undefined;
        readonly login?: string | undefined;
    } | undefined;
    isLoadingAuthInfo: readonly boolean;
    authInfoError: readonly unknown;
};
```

### Reproduction

Open [StackBlitz](https://stackblitz.com/edit/nuxt-repro-runtime-failed-types?file=src%2Fruntime%2Fstore%2Fstore.ts) and go to `dist/runtime/store/store.d.ts`

**Comment by danielroe** [comment]
Interesting. I wonder if this is an issue with `vue-tsc`, which is generating these types...

**Comment by alSergey** [comment]
@danielroe hi, did I understand correctly that I need to create an issue on `vue-tsc`? And how can I properly explain the problem to them, considering that I'm using `@nuxt/module-builder`, which uses `vue-tsc` somewhere under the hood?

**Comment by alSergey** [comment]
@danielroe Hi, is there any progress on this issue?

**Comment by alSergey** [comment]
@manniL hi, can you please tell me if there is any progress on this issue?

**Comment by alSergey** [comment]
@danielroe Hi, is there any progress on this issue?

**Comment by Neemsigo** [comment]
Looks like I have a similar problem

**Comment by danielroe** [comment]
This is how TS outputs the types:
![CleanShot 2024-09-10 at 14 46 20@2x](https://github.com/user-attachments/assets/372b8aa6-7e06-42e7-a73b-144850c93888)

```ts
export declare const useAuthInfo: () => {
    authInfo: Readonly<import("vue").Ref<{
        readonly userId?: number | undefined;
        readonly login?: string | undefined;
    } | undefined, {
        readonly userId?: number | undefined;
        readonly login?: string | undefined;
    } | undefined>>;
};
```

See https://stackblitz.com/edit/stackblitz-starters-ayewdt. It's not an issue with `@nuxt/module-builder`. Possibly an upstream one in https://github.com/vuejs/core.
