### ISSUE TITLE
can't prepack default generated module by nuxi 

### ISSUE THREAD

**Issue by nort3x** [nuxt/module-builder#321]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.3
- CLI Version:      3.11.1
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

```bash
nuxi init -t module my-module
cd my-module
yarn run prepack
```

zip containing default generated scaffold by nuxi

[reproduce.zip](https://github.com/user-attachments/files/16102999/reproduce.zip)

### Describe the bug

`yarn run prepack` halts with:

```
 failed to resolve "extends":"./.nuxt/tsconfig.json" in /m1/tsconfig.json
```

### Additional context

also tried to first do `nuxi prepare` to produce  `.nuxt` (which should be done by `prepack` if required!)  which resulted in:

```
module is a string value; tsconfig JSON must be parsed with parseJsonSourceFileConfigFileContent or getParsedCommandLineOfConfigFile before passing to createProgram
```

**Comment by brokuka** [comment]
any news ?

**Comment by danielroe** [comment]
You need to run `npm run dev:prepare`, not `nuxi prepare`, which is specified in the README and module author guide.

The error you're getting is likely caused by having an older version of `mkdist` installed - would you check your package lock and upgrade it manually if necessary?

**Comment by lihbr** [comment]
Can confirm, killing `node_modules`/lock file and ensuring you're running `mkdist` 1.5.4 or higher solved the issue 👌

**Comment by danielroe** [comment]
This will keep reoccurring until the next unbuild release due to package manager caching but I think we can mark closed for now.
