### ISSUE TITLE
`.d.ts` Files not generated for components with script setup

### ISSUE THREAD

**Issue by ThornWalli** [nuxt/module-builder#349]
Hello,

I have noticed that when a component with `<script setup>` is created, no `.d.ts` file is created for it.

Is there a reason for this and is it correct?

![image](https://github.com/user-attachments/assets/b0ec555d-dd6f-498e-a4c3-37da7215b05c)

Thanks!

**Comment by danielroe** [comment]
The reason is that `defineProps` and other macros in `<script setup>` need special handling and volar can do that at runtime.

Is it causing any issues for you?

**Comment by danielroe** [comment]
This is now resolved in `unbuild` v3 (and will be in the upcoming v1 release of module-builder).
