### ISSUE TITLE
"npm pack" distributes shims

### ISSUE THREAD

**Issue by RossComputerGuy** [nuxt/module-builder#35]
I've been working on Vista which is a Nuxt 3 module. Whenever I run `npm build`, all of the files are built and not stubbed. However, when I run `npm pack`, `dist/module.mjs` uses jiti to load and `dist/runtime` is a symlink instead of a directory. I've asked on Discord and got no-one to help so hopefully this can be solved here. The source code is available at https://github.com/MidstallSoftware/vista and if you want to see the issue for yourself, just download `@midstallsw/vista` from NPM.

**Comment by danielroe** [comment]
The issue is here with using the `prepare` script and it is a bug with npm, if I recall correctly. It is why we now use the `dev:prepare` script. But it's not an issue with `@nuxt/module-builder`.

My apologies for the very long delay in responding.
