### ISSUE TITLE
Current state of watch mode

### ISSUE THREAD

**Issue by Exotelis** [nuxt/module-builder#378]
Hi,

We're building a Nuxt module that we use across multiple projects. Often, we find ourselves wanting to test local changes without having to publish packages, etc. Typically, we use `npm link` for this, which works as expected. However, after making changes, we always have to run a build.

According to the source files of `@nuxt/module-builder`, there are settings for a watch feature, but they are flagged as @experimental.

Is there a timeline for this feature?

**Comment by danielroe** [comment]
There is no `watch` mode as such.

Instead, you run `nuxt-module-build build --stub` and you will be able to test/run your module without building it. (A stub in your dist directory is generated that uses `jiti` to import your source files - so you can directly test local changes without running a build.)
