### ISSUE TITLE
Importing from #imports results in a build-error

### ISSUE THREAD

**Issue by stenet** [nuxt/module-builder#40]
While trying to create a PR for #39 I did some further testing. My reexported module ```some-exports.ts``` now has an import from ```#imports```.

![image](https://user-images.githubusercontent.com/1838511/188827311-a1baa8f5-d102-4da1-b985-c253b71308f4.png)

When reexporting this module in ```module.ts``` some build-errors occur.

![image](https://user-images.githubusercontent.com/1838511/188827452-7d976f27-cfea-4a8b-b162-72d8a6896cc9.png)

```bash
 WARN  Inlining implicit external #imports    
Could not resolve import "#imports" in F:\Git\nuxt-type-export-module\src\runtime\some-exports.ts using imports defined in F:\Git\nuxt-type-export-module\package.json.

 WARN  Inlining implicit external #imports       
Could not resolve import "#imports" in F:\Git\nuxt-type-export-module\src\runtime\some-exports.ts using imports defined in F:\Git\nuxt-type-export-module\package.json.

 WARN  Inlining implicit external #imports        

 WARN  Inlining implicit external #imports         
'#imports' is imported by src/runtime/some-exports.ts, but could not be resolved – treating it as an external dependency

 ERROR  Package import specifier "#imports" is not defined in package F:\Git\nuxt-type-export-module\package.json imported from F:\Git\nuxt-type-export-module\dist\module.mjs  
```

### Reproduction

Sample [here](https://github.com/stenet/nuxt-type-export-module/blob/main/src/runtime/some-exports.ts).

In this case when I replace  ```#imports``` with ```vue``` the build works without any errors.
Should importing from ```#imports``` be avoided when creating a module or is this a bug?

**Comment by danielroe** [comment]
You can only import from `#imports` within code intended to be run within a Nuxt app. Moreover, Nuxt modules run in a different context and should not import from `#imports` and should not re-export their runtime code.

**Comment by stenet** [comment]
Thank you! Makes sense because ```#imports``` is part of ```./playground/.nuxt/types```. The weird thing is, that the my IDE (JetBrains) automatically uses ```#imports```.

Still having some problems when creating a module inside a monorepo with reexports (same warnings as above but this time with vueuse + vue-demi + other external libraries). Will do some further testing and maybe come back with something more specific later.
