### ISSUE TITLE
types dts difference build between Windows and Linux

### ISSUE THREAD

**Issue by userquin** [nuxt/module-builder#426]
Bulding the same module on Windows and Linux may result in different build result when building the module types dts.

The problem is upstream at `mlly`.

Check this issue at nuxt/i18n module: https://github.com/nuxt-modules/i18n/pull/3225#issuecomment-2474204973

Running the build in vite pwa nuxt integration, the result is the same in Linux and Windows: types are generated properly

**Comment by danielroe** [comment]
this should now be resolved!
