### ISSUE TITLE
Module failed to compile

### ISSUE THREAD

**Issue by casualmatt** [nuxt/module-builder#436]
### Environment

- Operating System: Linux
- Node Version:     v20.17.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

pnpm dlx nuxi init -t module my-module

or [nuxt-user-country module](https://github.com/JAMflow-Cloud/nuxt-user-country)

### Describe the bug

It's impossible to compile, and not even a clean nuxt module was generated by the starter project. 

### Logs

```shell-script
matteo@dev-container:~/git/jamflow/module$ pnpm prepack

> my-module@1.0.0 prepack /home/dev/git/jamflow/module
> nuxt-module-build build

ℹ Building my-module                                                                                                                                                                  5:11:23 PM
ℹ Cleaning dist directory: ./dist                                                                                                                                                     5:11:23 PM
.nuxt/components.plugin.mjs(3,1): error TS2742: The inferred type of 'default' cannot be named without a reference to '~/node_modules/nuxt/dist/app/nuxt.js'. This is likely not portable. A type annotation is necessary.


 ERROR  Failed to compile. Check the logs above.                                                                                                                                       5:11:25 PM

  at error (node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Object.error (node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
  at Object.error (node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:24472:42)
  at generateDtsFromTs (node_modules/.pnpm/rollup-plugin-dts@6.1.1_rollup@3.29.5_typescript@5.7.2/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1834:30)
  at Object.transform (node_modules/.pnpm/rollup-plugin-dts@6.1.1_rollup@3.29.5_typescript@5.7.2/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1843:38)
  at node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 



 ERROR  Failed to compile. Check the logs above.                                                                                                                                       5:11:25 PM

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by casualmatt** [comment]
Probably a duplicate of https://github.com/nuxt/module-builder/issues/141

**Comment by silvercent011** [comment]
@casualmatt 
On my machine, I encountered an error while building a module with Node 20 and @types/node version 22. Downgrading @types/node to the 20.x major version resolved the issue for me. I noticed in your reproduction that @types/node is set to version 22 in the pnpm-lock.yaml, but you're using Node 20. Maybe that's the issue.

**Comment by BobbieGoede** [comment]
We're getting the same error when trying to build the i18n module with `typescript@5.7.2` (https://github.com/nuxt-modules/i18n/actions/runs/12095017311/job/33856223860?pr=3251), it builds fine with `typescript@~5.6`.

I have checked and installing `typescript@~5.6` in the reproduction will fix the error described, though it will still fail due to other unrelated issues.

**Comment by danielroe** [comment]
This is likely caused by https://github.com/vuejs/language-tools/issues/5018.

**Comment by sandros94** [comment]
Oh, for some reason I wasn't subbed to this and didn't see @BobbieGoede's message. Indeed it fixes the build issue for `nuxt-user-country` and new modules from Nuxt's starters.

Thanks @danielroe, subbing there to track that issue.

**Comment by amery** [comment]
still happening 😭

**Comment by sandros94** [comment]
> still happening 😭

even if you pinned typescript to `5.6.3` and vue-tsc to `2.1.6`?

**Comment by amery** [comment]
> > still happening 😭
> 
> even if you pinned typescript to `5.6.3` and vue-tsc to `2.1.6`?

Thanks, I had only downgraded typescript
