### ISSUE TITLE
Use others modules as helper to create others modules

### ISSUE THREAD

**Issue by calebeaires** [nuxt/module-builder#44]
I am building a Module and I would like to use others modules while building it: (like @pinia/nuxt). My goal is not to force the end user to install those others libs. In this way the Nuxt config file is not created in playground, but in the project itself. I tried to create a nuxt.config.js file to import this @pinia/nuxt, but Is does not. 

```ts
import {defineNuxtConfig} from 'nuxt'
export default defineNuxtConfig({
  imports: {
    autoImport: true
  },
  modules: [
    '@pinia/nuxt'
  ],
})

```

Do I have to use Nuxt Modules hooks make it work? if yes, can you guys help get there!

My start point were: [Start Module](https://github.com/nuxt/starter/tree/module)

**Comment by cpreston321** [comment]
@calebeaires have you tried https://v3.nuxtjs.org/api/advanced/kit#modules `installModule()` ? 

kit code [here](https://github.com/nuxt/framework/blob/b933015850ff68debbe8c950418e4d5c49127634/packages/kit/src/module/install.ts#L8)

I would install as a **dep** in your module then try doing this 

```ts [module.ts]
import { defineNuxtModule, installModule } from '@nuxt/kit'

export interface ModuleOptions {
  apiKey: string
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'my-module',
    configKey: 'myModule'
  },
  defaults: {
    apiKey: null
  },
  async setup (_options, _nuxt) {
    await installModule('@pinia/nuxt', {
      // pina options
    })

    // Your code below here
  }
})
```

I have not tried this but it's worth a shot 😄
