### ISSUE TITLE
Add possibility to resolve and inline imported `devDependencies`

### ISSUE THREAD

**Issue by s1gr1d** [nuxt/module-builder#445]
Sometimes, `devDependencies` are not published as they are only used locally. It would be a nice feature to inline the imports of those dependencies, so those do not have to be inlined manually (meaning, the import of the package is removed and the function is written directly into the file).

**Comment by danielroe** [comment]
This would need to be solved in https://github.com/unjs/mkdist.

**Comment by pi0** [comment]
mkdist if file-by-file transformer (not bundler). an additional (rollup) entry needed for this. There are alternatives such as conditional exports.

Having better description of why this is a requirement, might help.

**Comment by danielroe** [comment]
I added the label to explain that this is not something we can resolve in nuxt/module-builder, but of course it doesn't mean that it _has_ to be implemented in `mkdist`.

**Comment by pi0** [comment]
https://github.com/unjs/mkdist/issues/263

**Comment by danielroe** [comment]
great - let's track there 🙏 

@s1gr1d I think @pi0 is happy to reopen with some more context - I'll provide what I know and you may have more helpful comments...

**Comment by s1gr1d** [comment]
@pi0 For more context: When importing something from a local package (which is added as a `devDependency`), it would be nice to inline the imported code during build-time. Otherwise, an error is thrown in user-land, as the import from the local package is preserved as-is and it cannot be fetched from npm.

why might this be needed?
- when the Nuxt module is created in a mono-repository and a local-only `devDependency` is added.

how commonly is this needed?
- that, I unfortunately cannot answer, but this is possible when building with rollup and using plugins

**Comment by pi0** [comment]
Thanks for further explanation dear @s1gr1d. 

The way we set the conventional standards for `dist/runtime/` across nuxt, nitro is that these files are not-pre-bundled, prepared to be **ingested** to the user build (vite or roll-up) with a clear module graph, and also explicitly separated from rest of `dist/*` which are build-time files.

When authoring Nuxt/Nitro integrations, dependencies (especially runtime) should be explicitly specified in `dependencies` or `peerDependencies`.

Of course, there is the possibility that a specific requirement needs it, and in that case, you can add an explicit rollup entry in `build.config` file to emit runtime dist.

I would be happy to explain and help further for the particular case in Sentry SDK and possibly at least document solutions for similar cases in module builder.
