### ISSUE TITLE
`vue-demi` postinstall script

### ISSUE THREAD

**Issue by sadeghbarati** [nuxt/module-builder#52]
Thanks, Pooya for this module @pi0 
 

What if Vue package that uses `vue-demi` needs to switch or redirect the version on `postinstall` script

as `vue-demi` respect these Vue versions: `2.6.14` - `2.7` - `3`, I want the same behavior on my Vue package too

- package use `expose` API, expose API is not present is vue2.6.14 even with [@vue/composition-api](https://github.com/vuejs/composition-api) 
https://github.com/vuejs/composition-api/issues/936

- **Vue 2.6.14** sample code

```ts
export default  defineComponent({
  emits: {
    'before-mount': () => true,
  },
  setup(props, { emit }) {
   const exposeRef = ref()
   // ...
   return {
      exposeRef // public ref or functions
    }
  },
  render() {
    // event forwarding vue 2.6.14 this.$listeners @click @events
    return h(this.$props.as || 'div', { ref: 'target', on: this.$listeners }, [
      h('div', this.$slots.default),
    ])
  },
})
```

- **Vue 2.7 and 3**

```ts
export default defineComponent({
  emits: {
    beforeMount: () => true,
  },
  setup(props, { emit, expose, slots }) {
   const exposeRef = ref()
   // ...
   expose({
      exposeRef
   })
   return (() => {
      return h(props.as || 'div', { ref: target }, slots.default && slots.default())
    }) as unknown as { exposeRef : typeof exposeRef } // expose type definition in defineComponent, thanks to johnsoncodehk for the tip
  },
})
```

Btw I want to create **Nuxt Module** based on that **Vue** package

---

@antfu I open this issue cause I have seen a lot of projects still on v2.6

**Comment by antfu** [comment]
It's just not possible to have `expose` in Vue 2.6. I think you either need to avoid using it or ask users to use 2.7 or 3.

Close as I consider the issue it not related to this repo.
