### ISSUE TITLE
mjs and newer ES syntax not supported in Nuxt2

### ISSUE THREAD

**Issue by dwightjack** [nuxt/module-builder#84]
I am trying to make a module compatible with both Nuxt2 and Nuxt3 using the module template provided by `npx nuxi init -t module <module-name>` but I am having a hard time understanding how to make it work with Nuxt2.

I have created a reproduction here: https://github.com/dwightjack/my-nuxt-module

The basic structure of the module is:
- a `module.ts` file that conditionally loads a [vue2 or vue3 plugin](https://github.com/dwightjack/my-nuxt-module/blob/main/src/module.ts#L17-L20)
- the plugins import a shared class that [uses the optional chaining syntax](https://github.com/dwightjack/my-nuxt-module/blob/main/src/runtime/my-class.ts#L13) (`?.`)

When I run `npm pack` on the module and try it on a Nuxt2 clean install, I receive the following errors:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/104721/208824430-13277bae-b54d-4d04-aa54-dc6b52749fc5.png">

1. Nuxt2 is unable to load `mjs` files or at least it is unable to understand that they are ES Modules
2. Nuxt2 does not understand optional chaining.

My guess is that the build tool is assuming compatibility only for Nuxt3, ignoring the issues that could arise with Nuxt2 so, at the moment, this tool is not very useful to develop modules compatible with multiple Nuxt versions. Is there a way to fix these issues? 

I guess that, to support mjs files we could do:

```
if (isNuxt2()) {
      addPlugin(resolve(runtimeDir, 'plugin.vue2'));
      extendWebpackConfig((config) => {
        config.module.rules.push({
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto'
        });
      });
    } else {
```

But these lines should be injected by the builder, I guess.

**Comment by harlan-zw** [comment]
The optional chaining issue you can resolve by telling Nuxt to transpile the dir / lib.  `build.transpile`

Also: 

> Nuxt 2 is functional but not advised

I'd recommend just making a separate package or export for the nuxt 2 module. You can simply use a js file and avoid any of these issues, it's not nice but it's easier than messing around with the breaking changes and type issues.

**Comment by dwightjack** [comment]
Thanks for your suggestions! 

> You can simply use a js file and avoid any of these issues

Then maybe i could have the nuxt 2 plugin in a dedicated folder in commonjs format, plain JavaScript and simply reference it in the addPluing function, right? That seems a reasonable solution.
