### ISSUE TITLE
Import & Type issues when developing new modules for Nuxt 3

### ISSUE THREAD

**Issue by ivodolenc** [nuxt/module-builder#85]
Hi, probably a known issue, but after researching, I didn't find a concrete answer on how to solve it well.

When developing modules, problems occur when using aliases (`#app`, `#imports`, `#head`) in `playground/` or module `src/runtime/` directories.

I came across this [comment](https://github.com/johnsoncodehk/volar/issues/586#issuecomment-1199837026) while looking for a solution.

If `./src` is added to the `include` options in the `<root>/tsconfig.json` file,

```json
{
  "extends": "./playground/.nuxt/tsconfig.json",
  "include": ["./src"]
}
```

then auto-imported composables (like `useHead` or `useAppConfig` etc.) in the all `.vue` files shows errors in the terminal:

```txt
Cannot find name '...'. Did you mean '...'?
```

This can be solved with explicit imports, but then there are no types (new type of errors).

Also, if I remove `./src` from tsconfig, then I have problems with `ModuleOptions` types and with the imports inside `src/runtime/` directory.

If needed, I can provide a link to a minimal example repo that shows the issue.

Any advice how to solve this? It is very annoying and time consuming when developing new modules for Nuxt 3.

**Comment by harlan-zw** [comment]
The types aren't perfect in my IDE (PHPStorm), but I can't replicate the issue you're having with the default config. Assuming you've ran `nuxi prepare playground`.

![image](https://user-images.githubusercontent.com/5326365/211004628-7fcfd5e2-dba6-462a-b169-1ea8b8ecc9f6.png)


Could you provide some details about your IDE and setup?

**Comment by atinux** [comment]
Feel free to reopen when answering to Harlan

**Comment by ivodolenc** [comment]
Sorry for the late reply.

> Assuming you've ran nuxi prepare playground

It throws an error after I run this so I haven't spent too much time debugging.

```txt
Cannot find package '@nuxt/kit' imported from /usr/local/lib/node_modules/nuxi/dist/chunks/prepare.mjs
```

> Could you provide some details about your IDE and setup?

Yep, sure:

- macOS: `Ventura 13.0.1`
- vscode: `1.74.2`
- volar: `1.0.24`
- node: `18.12.1`
- npm: `9.1.2`
- nuxt: `3.1.2`
- module-builder: `0.2.1`

**Comment by harlan-zw** [comment]
Do you have the `@nuxt/kit` dependency in your package.json?

**Comment by ivodolenc** [comment]
> Do you have the `@nuxt/kit` dependency in your package.json?

Yes, of course, I tried (@nuxt/kit v3.1.2) both with `dependencies` and with `devdependencies` but throws error.

Here are full message:

```
Nuxi 3.0.0 
ERROR  Cannot find package '@nuxt/kit' imported from /usr/local/lib/node_modules/nuxi/dist/chunks/prepare.mjs 

at new NodeError (node:internal/errors:393:5)
at packageResolve (node:internal/modules/esm/resolve:860:9)
at moduleResolve (node:internal/modules/esm/resolve:909:20)
at defaultResolve (node:internal/modules/esm/resolve:1124:11)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
at link (node:internal/modules/esm/module_job:75:36)
``` 

But like I said, the module works as expected and I can work normally in dev mode, but as soon as I try to use one of the nuxt import `#aliases`, then it throws ts errors.

It depends on the settings I use, whether they are used in the `runtime` or the `playground` directories. I've noticed the same issues with a few modules I've made for Nuxt 3.

Might be something with `volar`, I found a few issues on their repo with similar reports of ts aliases.

I don't have much time to deal with it right now so I wouldn't want to bore you with this. But thanks for the answers.
