### ISSUE TITLE
Prepack fails - `Syntax Errror: Unexpected token`

### ISSUE THREAD

**Issue by ineshbose** [nuxt/module-builder#86]
This is happening when trying to import a type definition from `unimport`.

Reproduction:
https://stackblitz.com/edit/github-8ln5yh?file=src/module.ts

`npm run dev:prepare && npm run prepack`

**Comment by harlan-zw** [comment]
I believe the issue is that you need to explicitly add `unimport` as a dependency if you're going to reference its type. See https://stackblitz.com/edit/github-8ln5yh-t1kod6?file=package.json,src%2Fmodule.ts

**Comment by ineshbose** [comment]
Hi, thanks for helping. I tried that but I believed that since I'm importing a type, it would be a dev dependency. I'll keep it in standard ones - thank you!

**Comment by harlan-zw** [comment]
Hey @ineshbose. Let me try and explain the issue properly, it has caught me out a number of times.

You're exporting types from your module (the module config), which depends on the unimport types.

You would think that TypeScript is smart enough to figure that the end-user will have these types automatically, but it doesn't work like that. Instead, it tries to inline them, but it fails when parsing the file (the syntax error), at least that's my understanding.

When you add it as a dependency it knows that the end user will have them so it doesn't need to do anything.

The proper fix is actually just to mark unimport as external within package.json and add it as a dev dependency (although you may not even need this).

Build is config for https://github.com/unjs/unbuild

```json
 "build": {
    "externals": [
      "unimport"
    ]
  },
```

See https://stackblitz.com/edit/github-8ln5yh-t1kod6?file=package.json

**Comment by sandros94** [comment]
Sorry to bother, but what about types that are coming from nuxt's aliases?

like for example:
```ts
import type { AsyncDataOptions } from '#app'
```

**Comment by harlan-zw** [comment]
> Sorry to bother, but what about types that are coming from nuxt's aliases?
> 
> like for example:
> 
> ```ts
> import type { AsyncDataOptions } from '#app'
> ```

These should not be processed by a bundler, they should only exist within the runtime folder and not reference from the module.ts itself

**Comment by sandros94** [comment]
> These should not be processed by a bundler, they should only exist within the runtime folder and not reference from the module.ts itself

This is quite interesting, and made me realize couple of error I was doing. Yes the issue was that I was importing my ModuleOptions from `./runtime/types/` instead of the specific file where they were exported. So the bundler probably started scanning all the other types and imports.

Once changed to `./runtime/types/module-options` even my initial `Unexpected token` error was gone.

[Reference](https://github.com/Sandros94/nuxt-directus/commit/f8b448bfade2aebedffda9f374d30331b5b1e5ea).
