### ISSUE TITLE
HMR for Nuxt modules

### ISSUE THREAD

**Issue by hoersamu** [nuxt/module-builder#88]
Is there a way to enable HMR for modules?
I'm trying to set up a Monorepo with multiple Nuxt instances powered by a shared component/composable library using a Nuxt module, but i can't seem to get HMR to work.
Since HMR for module files doesn't even work for the example app in the ./playground folder it seems to be a more basic problem with modules.

**Comment by atinux** [comment]
If you are looking to share Nuxt parts from the app part (composables, components, plugins, etc). I suggest you to look at [Nuxt Layers](https://nuxt.com/docs/guide/going-further/layers) that supports HMR.
