### ISSUE TITLE
Runtime Plugin types as `any` after `nuxt-module-build`; possibly `#app` is unresolved on build

### ISSUE THREAD

**Issue by akasection** [nuxt/module-builder#93]
## Problem
When we build a module with runtime plugin (and the plugin provides a provider via `return { provide }`), the plugin type becomes `any`, instead of provided type.

## Reproduction

```
> pnpx nuxi init -t module sample-nuxt-module
> pnpm i
> pnpm add pino
> (go to src/runtime/plugin.ts) and edit:
> 
import { defineNuxtPlugin } from '#app'
import Pino from 'pino'

export default defineNuxtPlugin((nuxtApp) => {
  console.log('Plugin injected by my-module!')
  const log = Pino()

  return {
    provide: {
      log
    }
  }
})

> pnpm pack / pnpm nuxi-module-build
> (go to /dist/runtime/plugin.d.ts)
```

Sandbox: https://codesandbox.io/p/sandbox/sample-nuxt-module-build-ts-bug-xnk8ev
## Expected
```typescript
declare const _default: import("nuxt/app").Plugin<{
    log: import("pino").Logger<import("pino").LoggerOptions | import("pino").DestinationStream>;
}>;
export default _default;
```
## Actual
```typescript
declare const _default: any;
export default _default;
```
## Info

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.5.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

## Additional Info

- If we change the import from `#app` to `nuxt/app`. The type now works, but it leads to this problem: https://github.com/nuxt/nuxt/issues/14801
- `#imports` also falls to same effect

**Comment by akasection** [comment]
hello @pi0 can this be addressed? 

sorry for mentioning tho

**Comment by artmizu** [comment]
I faced this issue too

Alias import like #app and #imports won't work correctly in the end, because i think they will be used in the actual app in the build step.

**Comment by trandaison** [comment]
Any workaround for this issue?
I ran into a same problem.
My module https://github.com/trandaison/nuxt-3-auth
This is the error log when run `npm run prepack`

![Screenshot 2024-03-19 at 11 17 13](https://github.com/nuxt/module-builder/assets/13447235/d3d0f226-b7d3-4e0b-9f36-73d7c2140cb8)

The log says that `AuthStorage.ts` has an import `#app` statement. However, I even don't use it in my code.
