### ISSUE TITLE
Module builder doesn't support script and script setup both using lang Typescript

### ISSUE THREAD

**Issue by spnc-omz** [nuxt/module-builder#96]
## Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `vite`, `pages`, `modules`, `postcss`
- Runtime Modules:  `test-nuxt-component-library@1.0.0`
- Build Modules:    `-`
------------------------------ 

    "@nuxt/module-builder": "^0.2.1",

```

## Reproduction
https://stackblitz.com/edit/github-5hu5z1?file=package.json

using this stackblitz, you can run `npm run prepack` to recreate the module.

## Describe the bug
When using module builder and pairing that with script setup AND script in the same vue sfc, both using lang=ts in an effort to disable 'inheritAttrs', a consuming nuxt project complains because the compiled nuxt module drops the lang on the script only tag.

The problem can be reviewed in dist/runtime/components/mySelect.vue in the reproduction link. 

[Vue sfc script setup alongside normal script](https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script)

The consuming nuxt app throws the following error:
```
[plugin:vite:vue] [@vue/compiler-sfc] <script> and <script setup> must have the same language type. 
```

I've included a second component, an input, that uses the option Api and doesn't experience this problem. But again, the problematic component is the select with the attributes manipulation. 

I believe the issue might be related to mkdist https://github.com/unjs/mkdist/issues/14 ? but i'm very unsure. 

Thanks!

**Comment by danielroe** [comment]
You can follow this issue upstream at https://github.com/unjs/mkdist/issues/22.

**Comment by spnc-omz** [comment]
I believe Vue 3.3 makes this issue no longer relevant. 

The ability to `defineOptions({inheritAttrs:false})` means we no longer need to have <script> and <script setup>

My updated stackblitz.

https://stackblitz.com/edit/github-5hu5z1-yshhdv?file=src%2Fruntime%2Fcomponents%2FmySelect.vue 

Should I close this issue?

**Comment by danielroe** [comment]
This is also no longer reproducible as `mkdist` doesn't process files with `<script setup>` blocks.
